# Generated by Django 4.2.10 on 2024-03-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customersDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Job', models.CharField(max_length=10)),
                ('Marital', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced')], default='Single', max_length=10)),
                ('Education', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('tertiary', 'tertiary'), ('unknown', 'unknown')], default='unknown', max_length=10)),
            ],
        ),
    ]
