# Generated by Django 4.2.10 on 2024-03-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='Balance',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='Campaign',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='Contact',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='Day',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='Duration',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='Housing',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='Loan',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='Month',
            field=models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('July', 'July'), ('Aug', 'Aug'), ('Sept', 'Sept'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='pdays',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='poutcome',
            field=models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='previous',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='customersdetailsmodel',
            name='Job',
            field=models.CharField(choices=[('admin', 'admin'), ('blue-collar', 'blue-collar'), ('entrepreneur', 'entrepreneur'), ('housemaid', 'housemaid'), ('management', 'management'), ('retired', 'retired'), ('self-employed', 'self-employed'), ('services', 'services'), ('student', 'student'), ('technician', 'technician'), ('unemployed', 'unemployed'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
    ]
